# Generated by Django 5.2.5 on 2025-09-24 17:09

import django.db.models.deletion
import django.utils.timezone
import export_panel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('shrimp_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Package Weight (Kg)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Number of Packages')),
                ('production_date', models.DateField(default=django.utils.timezone.now, verbose_name='Production Date')),
                ('expiration_date', models.DateField(default=export_panel.models.default_expiration_date, verbose_name='Expiration Date')),
                ('batch_number', models.CharField(max_length=100, unique=True, verbose_name='Batch Number')),
                ('qr_code', models.ImageField(blank=True, upload_to=export_panel.models.qr_code_path, verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exporting_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.exportingcompany', verbose_name='Exporting Company')),
                ('farming_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.shrimpfarmingcompany', verbose_name='Farming Company')),
                ('shrimp_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='shrimp_panel.shrimpproduct')),
            ],
            options={
                'verbose_name': 'Product Package',
                'verbose_name_plural': 'Product Packages',
                'ordering': ['-created_at'],
            },
        ),
    ]
