# Generated by Django 5.2.5 on 2025-09-24 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShrimpProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Weight (Kg)')),
                ('shrimp_type', models.CharField(max_length=255, verbose_name='Shrimp Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Price')),
                ('support_code', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Support Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='authentication.shrimpfarmingcompany')),
            ],
            options={
                'verbose_name': 'Shrimp Product',
                'verbose_name_plural': 'Shrimp Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestsProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_code', models.CharField(max_length=50, verbose_name='Support Code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='Request Status')),
                ('operation_date', models.DateTimeField(auto_now_add=True, verbose_name='Operation Date')),
                ('buyer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='authentication.exportingcompany', verbose_name='Buyer Company (Exporter)')),
                ('owner_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_requests', to='authentication.shrimpfarmingcompany', verbose_name='Owner Company (Farming)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shrimp_panel.shrimpproduct', verbose_name='Requested Product')),
            ],
            options={
                'verbose_name': 'Product Request',
                'verbose_name_plural': 'Product Requests',
                'ordering': ['-operation_date'],
            },
        ),
        migrations.AddIndex(
            model_name='shrimpproduct',
            index=models.Index(fields=['support_code'], name='shrimp_pane_support_f1fc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='shrimpproduct',
            index=models.Index(fields=['shrimp_type'], name='shrimp_pane_shrimp__20671a_idx'),
        ),
        migrations.AddIndex(
            model_name='shrimpproduct',
            index=models.Index(fields=['created_at'], name='shrimp_pane_created_56f372_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsproduct',
            index=models.Index(fields=['status'], name='shrimp_pane_status_fc8b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsproduct',
            index=models.Index(fields=['support_code'], name='shrimp_pane_support_fd0943_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsproduct',
            index=models.Index(fields=['operation_date'], name='shrimp_pane_operati_626f46_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsproduct',
            index=models.Index(fields=['buyer_company'], name='shrimp_pane_buyer_c_669abd_idx'),
        ),
        migrations.AddIndex(
            model_name='requestsproduct',
            index=models.Index(fields=['owner_company'], name='shrimp_pane_owner_c_c185ad_idx'),
        ),
    ]
