# Generated by Django 5.2.5 on 2025-09-24 17:09

import authentication.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('ceo_name', models.CharField(max_length=255, verbose_name='CEO Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('address', models.TextField(verbose_name='Company Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=authentication.models.company_logo_path, verbose_name='Company Logo')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Exporting Company',
                'verbose_name_plural': 'Exporting Companies',
            },
        ),
        migrations.CreateModel(
            name='ShrimpFarmingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('ceo_name', models.CharField(max_length=255, verbose_name='CEO Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('address', models.TextField(verbose_name='Company Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=authentication.models.company_logo_path, verbose_name='Company Logo')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Shrimp Farming Company',
                'verbose_name_plural': 'Shrimp Farming Companies',
            },
        ),
    ]
